WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE TABLESPACE TS_ACADEMIA DATAFILE 'ts_academia.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;
CREATE TABLESPACE TS_CLINICA DATAFILE 'ts_clinica.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;
CREATE TABLESPACE TS_RETAIL DATAFILE 'ts_retail.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;
CREATE TABLESPACE TS_LOGISTICA DATAFILE 'ts_logistica.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;
CREATE TABLESPACE TS_FINTECH DATAFILE 'ts_fintech.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE USER USR_ACADEMIA IDENTIFIED BY "Academia_Pass2026!" DEFAULT TABLESPACE TS_ACADEMIA;
GRANT CONNECT, RESOURCE, CREATE VIEW TO USR_ACADEMIA;
ALTER USER USR_ACADEMIA QUOTA UNLIMITED ON TS_ACADEMIA;

CREATE USER USR_CLINICA IDENTIFIED BY "Clinica_Pass2026!" DEFAULT TABLESPACE TS_CLINICA;
GRANT CONNECT, RESOURCE, CREATE VIEW TO USR_CLINICA;
ALTER USER USR_CLINICA QUOTA UNLIMITED ON TS_CLINICA;

CREATE USER USR_RETAIL IDENTIFIED BY "Retail_Pass2026!" DEFAULT TABLESPACE TS_RETAIL;
GRANT CONNECT, RESOURCE, CREATE VIEW TO USR_RETAIL;
ALTER USER USR_RETAIL QUOTA UNLIMITED ON TS_RETAIL;

CREATE USER USR_LOGISTICA IDENTIFIED BY "Logistica_Pass2026!" DEFAULT TABLESPACE TS_LOGISTICA;
GRANT CONNECT, RESOURCE, CREATE VIEW TO USR_LOGISTICA;
ALTER USER USR_LOGISTICA QUOTA UNLIMITED ON TS_LOGISTICA;

CREATE USER USR_FINTECH IDENTIFIED BY "Fintech_Pass2026!" DEFAULT TABLESPACE TS_FINTECH;
GRANT CONNECT, RESOURCE, CREATE VIEW TO USR_FINTECH;
ALTER USER USR_FINTECH QUOTA UNLIMITED ON TS_FINTECH;

COMMIT;
